dbmedialab/reader-critics

.codeclimate.yml, .eslintrc.json, package.json, run/lint, src/test/frontend/ArticleEditForm/CoverageURLs.test.js, src/test/frontend/ArticleEditForm/FormReset.test.js, src/test/frontend/FeedbackFormContainer/Structure.test.js, src/test/frontend/test-tools-frontend.js
First commit enables the ESlint engine. This build is likely to fail, because a local lint run shows a whole lotta errors (95% formatting, though)
=> Codeclimate ESlint

webpack-admin.js, webpack-front.js, webpack.js
Solves [RC-98](https://dbmedialab.atlassian.net/browse/RC-98)
=> Common Webpack configuration

src/front/apiCommunication.ts, src/front/feedback/FeedbackContainer.tsx
Request with article version, read correct object from response
=> Fixed API communication

.gitignore, package.json, webpack.js
Solves [RC-108](https://dbmedialab.atlassian.net/browse/RC-108)
=> RC-108 - Implemented webpack-bundle-analyzer

src/test/app/MochaSetup.test.ts, src/test/base/MochaSetup.test.ts, src/test/database/MochaSetup.test.ts, src/test/frontend/MochaSetup.test.ts
Changed from symlinked files to simple imports because of filesystem problems in M$ Windows
=> Fix Mocha test setup

package.json
=> Update @types/node to the version 8.0.19

src/front/component/ArticleElement.tsx
Solves [RC-50](https://dbmedialab.atlassian.net/browse/RC-50)
=> Fixed access to empty/undefined form field

src/app/db/models.ts, src/app/db/names.ts, src/app/db/schemas/ArticleSchema.ts, src/app/db/schemas/FeedbackSchema.ts, src/app/services/feedback/FeedbackDAO.ts, src/app/services/feedback/FeedbackService.ts, src/app/services/feedback/common/create.ts, src/base/Feedback.ts
Use a static enum for model names because distributed magic strings are a bad thing™
=> Database model names

resources/article/json/mopo.no_1.json5, resources/article/json/mopo.no_2.json5, src/app/db/schemas/FeedbackSchema.ts, src/app/routes/errorHandlers.ts, src/app/routes/fakeWidgetRoute.ts, src/app/routes/feedbackRoute.ts, src/app/routes/index.ts, src/app/util/errors.ts, tmp/templates/fake-widget.html
* A fake widget is available under `http://[hostname]/fake-widget/` that collects all necessary parameters to open a feedback page
* Feedback handler not supports GET and POST parameter handlers
* Feedback handler enforces version parameter
=> Fake widget and enforced version parameter

package.json
=> Update webpack to version 3.5.1

resources/article/json/dagbladet.no_67728317.json5, resources/feedback/demo-feedback-001.json5, resources/feedback/demo-feedback-002.json5, resources/feedback/demo-feedback-003.json5, src/app/services/feedback/FeedbackDAO.ts, src/app/services/feedback/FeedbackService.live.ts, src/app/services/feedback/FeedbackService.mock.ts, src/app/services/feedback/FeedbackService.ts, src/app/services/feedback/common/validateAndSave.ts, src/test/database/PersistingServices.test.ts, src/test/database/persisting-services/FeedbackServiceTests.ts
Solves [RC-149](https://dbmedialab.atlassian.net/browse/RC-149)
=> Feedback service: getByArticle()

package.json
=> Update ioredis to version 3.1.4

package.json
=> Update mocha to version 3.5.3

package.json
=> Update @types/react-redux to version 5.0.9

package.json
=> Update react-modal to version 2.3.2

README.md, package.json
Once more, clear out some dusty skeletons!
=> Fix dependencies

package.json
=> Update @types/mongoose to version 4.7.23

package.json
=> Update @types/react to version 16.0.7

package.json
=> Update @types/lodash to version 4.14.76

resources/article/html/ampbladet.no_68737640.html, resources/website/demo-sites.json5, src/app/parser/impl/AMPParser.ts, src/app/services/article/common/fetch.ts
Create a rudimentary AMP parser that extends the generic parser class. The result is working very well, only some extended elements are missing. These will be fixed in the next iteration.
=> Initial AMP parser

package.json
=> Update connect-redis to version 3.3.2

package.json, src/app/config.ts, src/app/mail/sendgrid/SendGridMailer.ts, src/app/queue/handlers/job.ts, src/app/routes/api/feedbackPostHandler.ts
Solves [RC-75](https://dbmedialab.atlassian.net/browse/RC-75)
=> RC-75 SendGrid Mailer

package.json
=> Update webpack to version 3.7.1

package.json
=> Update @types/node to version 8.0.41

package.json
=> Update webpack to version 3.8.1

package.json
=> Update @types/node to version 8.0.44

src/app/main/clusterSignals.ts, src/app/main/jobWorker.ts, src/app/main/master.ts, src/app/main/webWorker.ts
Makes the frontend tests start again, amongst other, very welcome things and effects.
=> Fix cluster startup

src/admin/components/modal/LoginModalComponent.tsx, src/admin/scss/custom/modals.scss
Removed unused validation from components in auth modal + fixed some scss classes
=> RC-203 - Removed unused validation from components in auth modal

package.json
=> Update @types/lodash to version 4.14.79

package.json
=> Update @types/bluebird to version 3.5.18

package.json
=> Update @types/express to version 4.0.39

package.json
=> Update node-sass to version 4.7.2

src/admin/components/layout/MainMenuComponent.tsx
[RC-210](https://dbmedialab.atlassian.net/browse/RC-210)
We want an other sort order of items in menu for admin UI
- Rearranged
- Nothing
Tests were not done because of simplicity of task. It can not break anything, just rearrange of links and titles
=> RC-210 - Rearrange menu in admin UI

src/app/db/schemas/WebsiteSchema.ts, src/base/Website.ts
Solves [RC-242](https://dbmedialab.atlassian.net/browse/RC-242)
=> RC-242 Feedback notification mail template in Website object

wercker.yml
Added `--no-optional` to the `npm install` stage, this might speed up things a little bit
=> Tests were commented out

package.json
=> Update nightwatch to version 0.9.19

src/app/routes/feedbackRoute.ts, src/front/apiCommunication.ts, src/front/component/ModalWindow.tsx, src/front/feedback/FeedbackContainer.tsx
[RC-199](https://dbmedialab.atlassian.net/browse/RC-199)
If article page doesn't exist we have to show a message for user in a modal, that something went wrond, but app crashes on it
- Fixed promise rejection inside another one promise rejection to get an error text
- Added react-intl wrapper for modal window to prevent getting an error that component is not wrapped by react-itl component while creation before implementation into react dom
- Nothing
Manually
=> RC-199 Unhandled 404 in Frontend

src/app/main/cron.ts, src/app/main/master.ts, src/app/main/mockFeedbackEvent.ts, src/app/queue/WorkerHandlers.ts, src/app/queue/handlers/onCheckAwaitFeedback.ts, src/app/queue/handlers/onNewFeedback/index.ts, src/app/queue/index.ts, src/app/services/feedback/dao/feedbackGet.ts
Solves [RC-246](https://dbmedialab.atlassian.net/browse/RC-246)
Cronjob that querys for feedback objects of status `await_enduser_data` which also have passed their wait timeout. All found feedback objects are pushed back into the queue to send their notification mail.
=> RC-246 Feedback await/trigger notification cronjob

package.json, src/front/common/Spinner.tsx, src/front/feedback/FeedbackContainer.tsx, src/front/scss/fb.scss, src/front/scss/layout/_spinner.scss
[RC-97](https://dbmedialab.atlassian.net/browse/RC-97)
Want to see a spinner while loading. It have to be able to implement into any page and preferable to be written on scss, not an image
- Added an npm package with a few different spinners
- Added import of scss styles
- Fixed some of them by our needs
- Nothing
Manually
=> RC-97 display spinner while loading

src/front/common/Footer.tsx, src/front/scss/pages/feedback/_fab.scss
[RC-250](https://dbmedialab.atlassian.net/browse/RC-250)
Need to remove all Data pointing on Dagbladet from Footer. Also need to fix Button for feedback ready to be in front of footer
- Removed blocks with text pointing on Dagbladet from footer
- Fixed scss for button
- Nothing
Manually
=> RC-250 Remove info about Dagbladet from footer

package.json, src/app/db/schemas/ArticleSchema.ts, src/app/db/schemas/FeedbackSchema.ts, src/app/routes/api/enduserHandler.ts, src/app/routes/api/feedbackHandler.ts, src/app/routes/apiRoute.ts, src/app/services/article/ArticleDAO.ts, src/app/services/article/ArticleService.live.ts, src/app/services/article/ArticleService.mock.ts, src/app/services/article/ArticleService.ts, src/app/services/enduser/EndUserDAO.ts, src/app/services/enduser/EndUserService.ts, src/app/services/feedback/FeedbackService.live.ts, src/app/services/feedback/FeedbackService.mock.ts, src/app/services/feedback/FeedbackService.ts, src/app/services/feedback/common/validateAndSave.ts, src/app/services/feedback/common/validateAndUpdateEnduser.ts, src/app/services/feedback/dao/feedbackGet.ts, src/app/services/feedback/dao/feedbackSave.ts, src/base/Feedback.ts, src/test/database/persisting-services/EndUserServiceTests.ts, src/test/database/persisting-services/FeedbackServiceTests.ts
Solves [RC-248](https://dbmedialab.atlassian.net/browse/RC-248)
* Reply with a one-shot update token
* Updated tests to reflect the new workflow
_PS: I couldn't find more labels to put on this PR, sorry_
=> RC-248 Push feedback without enduser data

src/app/mail/sendgrid/SendGridMailer.ts, src/app/routes/api/feedbackHandler.ts, src/app/services/feedback/common/validateAndUpdateEnduser.ts, src/base/api/RawPostEndUser.ts, src/front/apiCommunication.ts, src/front/feedback/FeedbackContainer.tsx, src/front/feedback/PostFeedbackContainer.tsx
Solves [RC-257](https://dbmedialab.atlassian.net/browse/RC-257) and hence [RC-211](https://dbmedialab.atlassian.net/browse/RC-211), finally!
=> RC-257 Break up workflow into two requests

src/front/suggest/SuggestionFormContainer.tsx
Render function too long, split it up!
=> Split up render()

package.json
=> Update moment to version 2.20.1

src/app/main/master.ts, src/app/util/applib/concurrency.ts
Solves [RC-124](https://dbmedialab.atlassian.net/browse/RC-124)
=> Calculate amount of web/job workers dynamically

src/app/main/cron.ts, src/app/queue/handlers/index.ts, src/app/queue/handlers/onCollectArticlesForPolling/onCollectArticlesForPolling.ts, src/app/queue/index.ts
Solves [RC-268](https://dbmedialab.atlassian.net/browse/RC-268)
=> Cronjob to trigger collecting articles for polling

src/app/main/cron.ts, src/app/queue/handlers/index.ts, src/app/queue/handlers/onCollectArticlesForPolling/PollParameters.ts, src/app/queue/handlers/onCollectArticlesForPolling/onCollectArticlesForPolling.ts, src/app/queue/handlers/onPollArticleUpdate/onPollArticleUpdate.ts, src/app/queue/index.ts, src/app/services/article/ArticleService.live.ts, src/app/services/article/ArticleService.mock.ts, src/app/services/article/ArticleService.ts, src/app/services/article/live/getIDsToPullUpdates.ts
Solves [RC-269](https://dbmedialab.atlassian.net/browse/RC-269)
=> RC-269 Article Update Collector

package.json, src/app/main.ts, src/app/util/applib/yell.ts
Solves [RC-265](https://dbmedialab.atlassian.net/browse/RC-265)
=> RC-265 Source Map Support

src/app/mail/getRecipients.ts
=> RC-272 Fix empty recipient list

src/front/feedback/PostFeedbackContainer.tsx, src/front/scss/pages/feedback/_postfeedbackform.scss
Solves [RC-278](https://dbmedialab.atlassian.net/browse/RC-278)
See also #658
=> Fix missing "Send" button on final feedback form

package.json, src/app/routes/admin/api/suggestionsHandler.ts
Solves [RC-280](https://dbmedialab.atlassian.net/browse/RC-280)
=> RC-280 Do not crash the Admin UI when there are no suggestions in the database

src/app/db/Redis.ts
Solves [RC-200](https://dbmedialab.atlassian.net/browse/RC-200)
=> RC-200 Check Redis connections URLs before trying to create a client

resources/localization.json5, resources/website/demo-sites.json5, src/admin/components/layout/MainMenuComponent.tsx, src/app/mail/layout/FeedbackFormat.ts, src/app/mail/layout/FeedbackNotifyLayout.ts, src/app/main/cron.ts, src/app/queue/handlers/onCollectArticlesForPolling/onCollectArticlesForPolling.ts, src/app/queue/handlers/onCompileUnrevisedDigest/layoutDigest.ts, src/app/queue/handlers/onCompileUnrevisedDigest/onCompileUnrevisedDigest.ts, src/app/queue/handlers/onSendEditorEscalation/layoutEscalationMail.ts, src/app/services/article/live/getUnrevised.ts, templates/mail/defaultUnrevisedDigest.html
Solves [RC-285](https://dbmedialab.atlassian.net/browse/RC-285)
=> RC-285 Redesign digest email

src/app/mail/sendgrid/SendGridMailer.ts
Filter out duplicate recipient addresses that reappear in the Bcc setting.
Solves [RC-286](https://dbmedialab.atlassian.net/browse/RC-286)
=> Filter duplicate recipients from Bcc

package.json
=> Update node-fetch to version 2.1.1

package.json
Closes #690
According to [NODE-1357](https://jira.mongodb.org/browse/NODE-1357) and [mongoose/History.md](https://github.com/Automattic/mongoose/blob/master/History.md#509--2018-03-05) the performance problem has been successfully solved. Let's try this with our setup here.
=> Update mongoose to version 5.0.9

package.json
=> Update node-sass to version 4.8.1

src/app/routes/admin/api/usersHandler.ts, src/app/services/user/UserDAO.ts, src/app/services/user/UserService.live.ts, src/app/services/user/UserService.mock.ts
Solves [RC-288](https://dbmedialab.atlassian.net/browse/RC-288)
=> Filter out anonymous user from ranged queries

package.json
=> Update query-string to version 6.0.0

src/app/queue/handlers/onNewFeedback/layoutNotifyMail.ts, templates/mail/allerFeedbackNotify.html, templates/mail/defaultEscalateToEditorNotify.html, templates/mail/defaultFeedbackNotify.html
https://dbmedialab.atlassian.net/browse/RC-293
=> Added link to article title

src/admin/components/website/additionalComponents/Label.tsx, src/admin/components/website/additionalComponents/LabeledInput.tsx, src/admin/components/website/additionalComponents/LabeledSelect.tsx, src/admin/components/website/additionalComponents/TagList.tsx, src/admin/components/website/modalParts/WebsiteEditors.tsx, src/admin/components/website/modalParts/WebsiteFeedbackEmailOverride.tsx, src/admin/components/website/modalParts/WebsiteHosts.tsx, src/admin/components/website/modalParts/WebsiteLayout.tsx, src/admin/components/website/modalParts/WebsiteLayoutContentSection.tsx, src/admin/components/website/modalParts/WebsiteName.tsx, src/admin/components/website/modalParts/WebsiteOverrideSettingsContentSection.tsx, src/admin/components/website/modalParts/WebsiteParserClass.tsx, src/admin/scss/custom/websites.scss, src/app/services/website/WebsiteDAO.ts
[Ticket ](https://dbmedialab.atlassian.net/browse/RC-295)
=> RC-295 Refactored components in website settings modal

.codeclimate.yml, resources/localization.json5, src/app/parser/AbstractIteratingParser.ts, src/app/parser/BaseItems.ts, src/app/parser/BaseIteratingItems.ts, src/app/parser/impl/sol/SolParser.ts, src/front/component/article-el/SectionParagraphElement.tsx, src/front/component/article-el/SectionTitleElement.tsx, src/front/component/createArticleElement.tsx, tslint.json
1. Add possibility to parse and mark properly  content inside tag <aside> on the vi.no. 
2. Add possibility to recognize announce text inside in the article
=> add section parsing

resources/article/html/sol.no_69933565.html, resources/article/json/sol.no_69933565.json5, resources/parser/ul-items.html, src/app/parser/util/CheerioPlugin.ts, src/test/app/parser/parser-aa-utils/CheerioPlugins.test.ts
=> Sol parser test

README.md, package.json, src/app/queue/handlers/onCompileUnrevisedDigest/onCompileUnrevisedDigest.ts, src/app/services/feedback/common/validateAndSave.ts, src/app/services/website/WebsiteDAO.ts
try to fix issue with updated pacckages
=> Develop fix update

package.json
Reverts dbmedialab/reader-critics#739
need to figure out how to attach react-dom.js to the template because the module structure is changed
=> Revert "Update react-dom to the latest version 🚀"

package.json
Reverts dbmedialab/reader-critics#824 There is no magic, even tests was passed..
=> Revert "fix(package): update webpack to version 4.18.0"

README.md, src/app/queue/handlers/onCompileUnrevisedDigest/onCompileUnrevisedDigest.ts, src/app/services/website/WebsiteDAO.ts, src/front/component/ModalWindow.tsx, webpack.js
To clean develop branch before merging to master
=> clean code

package.json
=> fix(package): update mongoose to version 5.3.4

src/admin/components/website/WebsitesGriddle.tsx, src/admin/components/website/modalParts/emailOverride/sectionOverride/WebsiteSectionEditors.tsx, src/admin/reducers/UIReducer.ts, src/admin/reducers/WebsiteReducer.ts, src/app/db/schemas/WebsiteSchema.ts
Because of changing Website data  structure - new fields was added, Website reducer merged state incorrect. 
Testing locally did not show this issue - because we create new data for testing, and they was maded according new structure.
=> Fix issue with website reducer and new data structure

src/front/feedback/PostFeedbackContainer.tsx
=> Fix loader

package.json
=> fix(package): update webpack to version 4.26.1

package.json
=> fix(package): update webpack to version 4.27.1

package.json
=> fix(package): update mongoose to version 5.4.0
